name: Build & publish to registry 

on:
  release:
    types: [published]

jobs:
  build_and_lint:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    container: ghcr.io/viam-modules/raspberry-pi:arm64
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - name: Verify no uncommitted changes from make lint
        run: |
          git init
          git add .
          chown -R testbot:testbot .
          sudo -u testbot bash -lc 'make lint'
          if [ -n "$GEN_DIFF" ]; then
              echo '"make lint" resulted in changes not in git' 1>&2
              git status
              exit 1
          fi

      - name: make module
        run: |
          sudo -u testbot bash -lc 'make module'
      
      - name: Upload
        uses: viamrobotics/upload-module@main
        with:
          module-path: bin/raspberry-pi-module.tar.gz
          platform: linux/arm64
          version: ${{ github.ref_name }}
          ref: ${{ github.sha }}
          key-id: ${{ secrets.VIAM_DEV_API_KEY_ID }}
          key-value: ${{ secrets.VIAM_DEV_API_KEY }}
