name: Pull Request Update

concurrency: 
  group: pullrequest-${{ github.head_ref }}
  cancel-in-progress: true

on:
  pull_request_target:
    branches: [ 'main' ]
    
jobs:
  test:
    uses: viam-modules/raspberry-pi/.github/workflows/test.yml@main