name: Test

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'README.md'

jobs:
  build_and_lint:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    container: ghcr.io/viam-modules/raspberry-pi:arm64
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - name: Verify no uncommitted changes from make lint
        run: |
          git init
          git add .
          chown -R testbot:testbot .
          sudo -u testbot bash -lc 'make lint'
          if [ -n "$GEN_DIFF" ]; then
              echo '"make lint" resulted in changes not in git' 1>&2
              git status
              exit 1
          fi

      - name: make build
        run: |
          sudo -u testbot bash -lc 'make build'

  test_on_pi:
    # The following steps are run on an external runner "rpibull"
    runs-on: pi-4
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v3
      - name: build
        run: make build

      - name: run tests
        run: make test
